### ISSUE TITLE
HiveError: Cannot write resource

### ISSUE THREAD

**Issue by ysavr** [SadaqaWorks/Quran-Flutter#33]
Assalamu Alaikum
I get below issues on the run 

`E/flutter (10082): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: Cannot write, unknown type: _$_Resource. Did you forget to register an adapter?
E/flutter (10082): #0      BinaryWriterImpl.write (package:hive/src/binary/binary_writer_impl.dart:337:9)
E/flutter (10082): #1      BinaryWriterImpl.writeList (package:hive/src/binary/binary_writer_impl.dart:223:7)
E/flutter (10082): #2      BinaryWriterImpl._writeList (package:hive/src/binary/binary_writer_impl.dart:389:7)
E/flutter (10082): #3      BinaryWriterImpl.write (package:hive/src/binary/binary_writer_impl.dart:328:7)
E/flutter (10082): #4      BinaryWriterImpl.writeFrame (package:hive/src/binary/binary_writer_impl.dart:281:9)
E/flutter (10082): #5      StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:127:31)
E/flutter (10082): #6      StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:123:28)
E/flutter (10082): #7      ReadWriteSync.syncWrite.<anonymous closure> (package:hive/src/backend/vm/read_write_sync.dart:26:41)
E/flutter (10082): #8      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (10082): #9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10082): <asynchronous suspension>
E/flutter (10082): #10     BoxImpl._writeFrames (package:hive/src/box/box_impl.dart:88:7)
E/flutter (10082): <asynchronous suspension>
E/flutter (10082): 
`

**Comment by mianumar5653** [comment]
Yes!! I also face the same issue. How could I resolve this error? anyone kindly help me.

**Comment by mianumar5653** [comment]
> Assalamu Alaikum I get below issues on the run
> 
> `E/flutter (10082): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: Cannot write, unknown type: _$_Resource. Did you forget to register an adapter? E/flutter (10082): #0 BinaryWriterImpl.write (package:hive/src/binary/binary_writer_impl.dart:337:9) E/flutter (10082): #1 BinaryWriterImpl.writeList (package:hive/src/binary/binary_writer_impl.dart:223:7) E/flutter (10082): #2 BinaryWriterImpl._writeList (package:hive/src/binary/binary_writer_impl.dart:389:7) E/flutter (10082): #3 BinaryWriterImpl.write (package:hive/src/binary/binary_writer_impl.dart:328:7) E/flutter (10082): #4 BinaryWriterImpl.writeFrame (package:hive/src/binary/binary_writer_impl.dart:281:9) E/flutter (10082): #5 StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:127:31) E/flutter (10082): #6 StorageBackendVm.writeFrames.<anonymous closure> (package:hive/src/backend/vm/storage_backend_vm.dart:123:28) E/flutter (10082): #7 ReadWriteSync.syncWrite.<anonymous closure> (package:hive/src/backend/vm/read_write_sync.dart:26:41) E/flutter (10082): #8 _rootRunUnary (dart:async/zone.dart:1436:47) E/flutter (10082): #9 _CustomZone.runUnary (dart:async/zone.dart:1335:19) E/flutter (10082): <asynchronous suspension> E/flutter (10082): #10 BoxImpl._writeFrames (package:hive/src/box/box_impl.dart:88:7) E/flutter (10082): <asynchronous suspension> E/flutter (10082): `

Assalamu Alaikum!!
 Sir, could you please tell me, if you find the answer to that error? If not then let me know if you have another solution?
 mianumar5653(github) (miaumar332@gmail.com),
Jazakallah

**Comment by wellRoundedAppDev** [comment]
> Yes!! I also face the same issue. How could I resolve this error? anyone kindly help me.

Brother did you reach the solution, please share if you did? God bless you.

**Comment by Shuhrat-java** [comment]
Same error....
